# Generated by Django 4.0.1 on 2022-03-06 08:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=100, null=True)),
                ('payment', models.CharField(max_length=100)),
                ('productImage', models.URLField(verbose_name='productimage')),
            ],
        ),
    ]
