# Generated by Django 4.0.1 on 2022-03-05 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(blank=True, max_length=100)),
                ('task_description', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('task_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SpecialTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stask_name', models.CharField(blank=True, max_length=100)),
                ('Stask_description', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('task_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SCompletedtasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(default=300)),
                ('CompletedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users')),
                ('t_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.specialtasks')),
            ],
        ),
        migrations.CreateModel(
            name='Completedtasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(default=300)),
                ('CompletedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users')),
                ('t_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.normaltasks')),
            ],
        ),
    ]
