# Generated by Django 4.0.2 on 2022-03-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NormalTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(blank=True, max_length=100)),
                ('task_description', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('task_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SpecialTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stask_name', models.CharField(blank=True, max_length=100)),
                ('Stask_description', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('task_date', models.DateField()),
            ],
        ),
    ]
