# Generated by Django 4.0.1 on 2022-03-05 06:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='username')),
                ('phone', models.CharField(max_length=13, verbose_name='phone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('score', models.IntegerField(default=0, verbose_name='score')),
                ('profileImage', models.URLField(blank=True, max_length=255, null=True, verbose_name='profileImage')),
            ],
        ),
    ]
